// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBB8TjEpIsIWZLjKsGi6ULmsWY6qregH8',
    appId: '1:787255316219:web:88e0451e3094fcd4d8ea5e',
    messagingSenderId: '787255316219',
    projectId: 'forever-pet-care',
    authDomain: 'forever-pet-care.firebaseapp.com',
    storageBucket: 'forever-pet-care.appspot.com',
    measurementId: 'G-RRZQV1FBCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RvC7k7-KmAEjIJ7YqsdfBPPcO7GmYQg',
    appId: '1:787255316219:android:2f8af6e808f63fe5d8ea5e',
    messagingSenderId: '787255316219',
    projectId: 'forever-pet-care',
    storageBucket: 'forever-pet-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-9RDqknqPhML0rpFKyg4gV09PNIkqAw',
    appId: '1:787255316219:ios:c5f485d38ac2fd2cd8ea5e',
    messagingSenderId: '787255316219',
    projectId: 'forever-pet-care',
    storageBucket: 'forever-pet-care.appspot.com',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-9RDqknqPhML0rpFKyg4gV09PNIkqAw',
    appId: '1:787255316219:ios:c5f485d38ac2fd2cd8ea5e',
    messagingSenderId: '787255316219',
    projectId: 'forever-pet-care',
    storageBucket: 'forever-pet-care.appspot.com',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBB8TjEpIsIWZLjKsGi6ULmsWY6qregH8',
    appId: '1:787255316219:web:6fcbc7b7b90411edd8ea5e',
    messagingSenderId: '787255316219',
    projectId: 'forever-pet-care',
    authDomain: 'forever-pet-care.firebaseapp.com',
    storageBucket: 'forever-pet-care.appspot.com',
    measurementId: 'G-PJLYT2WZ4L',
  );
}
